### ISSUE TITLE
Close Shutter as Freeze/Crash Protection

### ISSUE THREAD

**Issue by mkostuk** [mkostuk/MpS_Bugs#7]
Hi guys,

I experienced a new bug when running Mpscope3 
The data stops being taken (the frame number freezes) and the shutter stays open.

I have no way to know when it is happening expect if I stay in front of the screen the all time I image.
It happened twice today and I can't give you more info about how to reproduce it. If the error message rings a bell to you and you have an idea on hopw to avoid it, it would be great.

Also is there a way to implement a "close shutter" function when the program bugs?

Thanks !
Celine

Task Name: TaskMainAnaIn
Status Code: -200279
   at NationalInstruments.DAQmx.Internal.AnalogMultiChannelWaveformGenericReadAsyncResult.End()
   at NationalInstruments.DAQmx.Internal.AnalogMultiChannelReaderImpl.EndReadWaveformGeneric(IAsyncResult asyncResult)
   at NationalInstruments.DAQmx.AnalogMultiChannelReader.EndReadWaveform(IAsyncResult asyncResult)
   at MpScope.MpScanner.ProcessMainAnalogData(IAsyncResult ar) in C:\Users\DK\Dropbox\MpScope 3 - DEVELOPMENT\MpScope3\MpScope\MpScanner.cs:line 935
17:45:22:230   closing shutter
17:45:22:236   Closed Shutter in MpScanner.StopScanners()

**Comment by mkostuk** [comment]
Additional Log entries, at the start of the error:
17:37:05:840   Descanning  arbscan, frame is 200 x 20280 and scan is 4056000
17:37:05:967   Appending frames
17:37:18:007   Descanning  arbscan, frame is 200 x 20280 and scan is 4056000
17:37:31:251   Appending frames
17:37:41:195   Problem in process frames
17:37:41:450   disposed of digital counter
17:37:44:573   !!! Exception Thown: 
NationalInstruments.DAQmx.DaqException: Attempted to read samples that are no longer available. The requested sample was previously available, but has since been overwritten.

Increasing the buffer size, reading the data more frequently, or specifying a fixed number of samples to read instead of reading all available samples might correct the problem.

Property: NationalInstruments.DAQmx.DaqStream.ReadRelativeTo
Corresponding Value: NationalInstruments.DAQmx.ReadRelativeTo.CurrentReadPosition
Property: NationalInstruments.DAQmx.DaqStream.ReadOffset
Corresponding Value: 0

Task Name: TaskMainAnaIn

Status Code: -200279 ...

**Comment by mkostuk** [comment]
Calling MpLaserShutter.Close() inside the HandleNIException() function, BUT
I'm concerned that this just switches the shutter polarity ... need a way to verify shutter state.
